# TODO na razie zamiast bazy danych, do testów

categories = {
    "kaczmarski": "Kaczmarski & Gintrowski",
    "carols": "Kolędy",
    "common": "Obozowe",
    "patriotic": "Patriotyczne",
    "religious": "Religijne",
}

songs = {
    "kaczmarski": [
        "1788",
        "A my nie chcemy uciekać stąd",
        "Ambasadorowie",
        "Antylitania na czasy przejściowe",
        "Arka Noego",
        "Astrolog",
        "Autoportret Witkacego",
        "Ballada wrześniowa",
        "Bankierzy",
        "Cesarz",
        "Chrystus i kupcy",
        "Cromwell",
        "Damastes z przydomkiem Prokrustes mówi",
        "Dokąd nas zaprowadzisz, Panie",
        "Dylemat",
        "Dzieci Hioba",
        "Dzień gniewu",
        "Elekcja",
        "Encore, jeszcze raz",
        "Epitafium dla Sergiusza Jesienina",
        "Epitafium dla Sowizdrzała",
        "Epitafium dla Włodzimierza Wysockiego",
        "Gdy tak siedzimy",
        "Hiob",
        "Hymn",
        "Ifigenia",
        "Ismena",
        "Iwan Groźny",
        "Ja",
        "Jałta",
        "Judyta",
        "Kanapka z człowiekiem",
        "Kantyczka z lotu ptaka",
        "Kara Barabasza",
        "Karmaniola",
        "Karol Levittoux",
        "Kasandra",
        "Katyń",
        "Kniazia Jaremy nawrócenie",
        "Koniec wojny trzydziestoletniej",
        "Krajobraz po uczcie",
        "Krzyk",
        "Kuglarze",
        "Lament tytana",
        "Lekcja historii klasycznej",
        "Marcin Luter",
        "Margrabia Wielopolski",
        "Między nami",
        "Modlitwa o wschodzie słońca",
        "Mury",
        "Nasza klasa",
        "Nie lubię",
        "Niech…",
        "Obława",
        "Odpowiedź",
        "Pan Kmicic",
        "Pan Wołodyjowski",
        "Pejzaż z szubienicą",
        "Pejzaż zimowy",
        "Pieśń o śnie",
        "Piosenka żebracza",
        "Poczekalnia",
        "Pokolenie",
        "Pompeja II",
        "Poranek",
        "Potęga smaku",
        "Powrót",
        "Powrót z Syberii",
        "Prośba",
        "Prosty człowiek",
        "Przejście Polaków przez morze czerwone",
        "Przesłuchanie Anioła",
        "Przybycie tytanów",
        "Psalm o chlebie",
        "Requiem rozbiorowe",
        "Rokosz",
        "Rozmowa",
        "Rzeź niewiniątek",
        "Sen Katarzyny II",
        "Siedem grzechów głównych",
        "Śmiech",
        "Sprawozdanie z raju",
        "Stańczyk",
        "Stół Mordechaja Gebirtiga",
        "Strącanie aniołów",
        "Stworzenie świata",
        "Świadkowie",
        "Syn marnotrawny",
        "Szturm",
        "Tylko kołysanka",
        "U wrót doliny",
        "Upadek Związku Radzieckiego",
        "W ciemności do siebie idziemy",
        "Walka Jakuba z aniołem",
        "Warchoł",
        "Wędrówka z cieniem",
        "Wigilia na Syberii",
        "Wiosna 1905",
        "Włóczędzy",
        "Wojna postu z karnawałem",
        "Wróżba",
        "Zatruta studnia",
        "Zbroja",
        "Zesłanie studentów",
        "Zmartwychwstanie Mandelsztama",
        "Źródło",
    ],
    "common": [
        "1980 II",
        "997 (Halo panie policjancie)",
        "A ja nie",
        "A time for us",
        "A u nas latem",
        "Ach te baby",
        "Adagio",
        "Ai Se Eu Te Pego",
        "Ajrisz",
        "Ale to już było",
        "Anioł i diabeł",
        "Arahja",
        "Atomowe czarne chmury",
        "Autobusy i tramwaje",
        "Ave Maria Païen",
        "Ave Maria Païen (Accantus)",
        "Avinu Malkeinu",
        "Ballada o dzikim zachodzie",
        "Ballada o krzyżowcu",
        "Ballada o szczęściu",
        "Banderas",
        "Banderas (wersja dla środowisk zamkniętych)",
        "Baranek",
        "Barman",
        "Bawitko",
        "Będziesz moją panią",
        "Believer",
        "Belle (tł. Andrzej Ozga)",
        "Belle (tł. Dorota Kozielska)",
        "Belle (tł. Jacek Cygan)",
        "Bez słów",
        "Biała sukienka",
        "Biały kaftanik",
        "Biały krzyż",
        "Biały miś",
        "Biegłaś zboczem",
        "Bieszczady",
        "Bieszczadzki trakt",
        "Bieszczadzkie anioły",
        "Bijatyka",
        "Bitwa",
        "Boję się",
        "Bolero",
        "Bomba",
        "Boso",
        "Brzegi Nowej Szkocji",
        "Buka",
        "Bukowina II",
        "Burza",
        "Camille Claudelle",
        "Can’t help falling in love",
        "Chłopcy z Botany Bay",
        "Chodź pomaluj mój świat",
        "Chryzantemy złociste",
        "Ciągle za cienko",
        "Ciągnik",
        "Circle of Life",
        "Cóżem winien",
        "Cykady na Cykladach",
        "Cyniczne córy Zurychu",
        "Cyrk",
        "Czarny blues o czwartej nad ranem",
        "Czarny chleb i czarna kawa",
        "Czas powrotów",
        "Czekałem na Ciebie",
        "Czerwone korale",
        "Człowiek z liściem na głowie",
        "Cztery córy miał tata",
        "Czuże su te koné",
        "Dalej w morze",
        "Davy Jones",
        "Daybreak",
        "Deszczowe lato",
        "Dezyderata",
        "Dla Ciebie",
        "Długość dźwięku samotności",
        "Dni niczyje",
        "Dni, których nie znamy",
        "Do Ciebie Mamo",
        "Do Neptuna",
        "Dom na prerii",
        "Dom wschodzącego słońca",
        "Dozwolone od lat 18",
        "Droga na Smoleńsk",
        "Dumka na dwa serca",
        "Dyktator",
        "Dżdżownica",
        "Dziesięć w skali Beauforta",
        "Dziewczyna rumiankowa",
        "Dziś późno pójdę spać",
        "Dziś prawdziwych Cyganów już nie ma",
        "Dzwony",
        "Endless Night",
        "Epitafium dla Majora „Ognia”",
        "Every breath",
        "Falling Slowly",
        "Falling Slowly (Accantus)",
        "Father and Son",
        "Few days",
        "Fordewind",
        "Francis Villon (modlitwa)",
        "Freedom",
        "Futbol",
        "Gdzie ten, który powie mi",
        "Głupole",
        "Godzina między",
        "Godzina miłowania",
        "Grajmy Panu",
        "Granda",
        "Grønland",
        "Grzeczny Jan",
        "Grzywa",
        "Guldia",
        "Halaba-luby-lej",
        "Hallelujah",
        "Hallelujah (wersja polska)",
        "Halny",
        "Hanging tree",
        "Hanging tree (Accantus)",
        "Hawrań i Murań",
        "He Lives in You",
        "Hej bystra woda",
        "Hej Hanno",
        "Hej przyjaciele",
        "Hej, przygodo",
        "Hej, sokoły",
        "Hello",
        "Hiszpańskie dziewczyny",
        "Hoist the Colours",
        "House of the Rising Sun",
        "I Ciebie też, bardzo",
        "I won’t forget you",
        "I won’t forget you (wersja polska)",
        "Ja Sowa",
        "Jak",
        "Jak ja kocham Cię",
        "Jaka jesteś",
        "Jaskółka uwięziona",
        "Jasnowłosa",
        "Jedenaste",
        "Jesień w górach",
        "Jeśli ty nie istniałbyś",
        "Jeszcze w zielone gramy",
        "Jolka Jolka",
        "Jolly Roger",
        "Już dopala się ogień biwaku",
        "Kapitan Hak",
        "Kareta złota",
        "Katedr świat (Andrzej Ozga)",
        "Katedr świat (Robert Janowski)",
        "Katiusza",
        "Katyń 1940 (Ostatni list)",
        "Kawałek do Tańca",
        "Kilku kumpli weź",
        "Kim właściwie była ta piękna Pani",
        "King",
        "Kluski",
        "Knajpa morderców",
        "Kocham Cię jak Irlandię",
        "Kolęda żeglarska",
        "Kolorowy wiatr",
        "Kołysanka",
        "Kombajn Bizon",
        "Komu bije dzwon",
        "Krąg życia (Accantus)",
        "Krajka",
        "Krokodyle",
        "Kryzysowa narzeczona",
        "Kto powie mi jak",
        "Ktoś mnie pokochał",
        "Kwiaty",
        "Laleczka z Saskiej Porcelany",
        "Latarnik",
        "Lato",
        "Lato z komarami",
        "Lato z radiem",
        "Lawa",
        "Let it be",
        "Lewe lewe loff",
        "Lipka",
        "Lisom lisom",
        "List do Boga",
        "List do Małego Księcia",
        "Litania",
        "Los włóczęgi",
        "Lubię mówić z tobą (muczeć z krową)",
        "Ludzie to Adam i Ewa",
        "Ładownie",
        "Łemkowyna",
        "Łódki",
        "Łomianki",
        "Maciek, ja tylko żartowałem",
        "Majka",
        "Makatka szalona",
        "Maleńka",
        "Małgośka",
        "Małomiasteczkowy",
        "Marchewkowe pole",
        "Marco Polo",
        "Maria",
        "Mario, czy ty wiesz?",
        "Mary, did you know?",
        "Miasto",
        "Między nami tyle śniegu",
        "Miejcie nadzieję",
        "Mija rok",
        "Miła",
        "Miłość rośnie wokół nas",
        "Miłość to wierność wyborowi",
        "Miłość w Zakopanem",
        "Misty Mountains",
        "Mniej niż zero",
        "Modlitwa (Taniec Wampirów)",
        "Modlitwa końca mojego wieku",
        "Modlitwa wędrownego grajka",
        "Moja litania",
        "Moja miłość największa",
        "Moje koleżanki",
        "Morskie opowieści",
        "Morze, nasze morze",
        "Mówiłam żartem",
        "My cyganie",
        "My heart will go on",
        "Na jednej z dzikich plaż",
        "Na kolejowym szlaku",
        "Na orbicie serc",
        "Na zakręcie",
        "Naprawdę nie dzieje się nic",
        "Natalia w Bruklinie",
        "Nazywali go Marynarz",
        "Nie chcę więcej",
        "Nie daj mi odejść",
        "Nie ma nic",
        "Nie płacz Ewka",
        "Nie rozdziobią nas kruki",
        "Niebieskooka",
        "Niech mówią, że to nie jest miłość",
        "Niech żyje bal",
        "Niedźwiedź",
        "Niemożliwe",
        "Nim wstanie dzień",
        "Och życie, kocham Cię nad życie",
        "Od nocy do nocy",
        "Oddaj mi samotność",
        "Odpowie ci wiatr",
        "Only the very best (S.O.S.)",
        "Opadły mgły",
        "Orki z majorki",
        "Ostatnia nocka",
        "Pamiętnik apostoła",
        "Pazawi mienia cicha pa imieni",
        "Pedro",
        "Peggy brown",
        "Pejzaże Harasymowiczowskie",
        "Phantom of the opera",
        "Phantom of the opera (wersja polska)",
        "Pieśń gruzińska",
        "Pieśń wielorybników",
        "Pijmy wino za kolegów",
        "Piła Tango",
        "Piłem w Spale, spałem w Pile",
        "Piosenka bez tytułu",
        "Piosenka Mazowiecka",
        "Piosenka na przetrwanie",
        "Piosenki Bony M",
        "Plecak",
        "Płacz",
        "Płoną góry płoną lasy",
        "Płyńmy do Starej Maui",
        "Podanie o…",
        "Połoniny niebieskie",
        "Pożegnalny ton",
        "Pożegnanie",
        "Pożegnanie Liverpoolu",
        "Prawy do lewego",
        "Przebacz mi",
        "Przebudzenie",
        "Przechyły",
        "Przetańczyć z tobą chcę całą noc",
        "Przez Twe oczy zielone",
        "Przyjaciele",
        "Przyjdź z Libanu",
        "Psalm dla Ciebie",
        "Quo Vadis, Domine?",
        "Radioactive",
        "Radość o poranku",
        "Rains of Castamere",
        "Rolling in the deep",
        "Rozbójnik",
        "Rudy Frank",
        "Rudy gość",
        "Ruty Siuty",
        "S.O.S. d’un Terrien en détresse",
        "Samantha",
        "Sandały",
        "Santiana",
        "Say Something",
        "Ściernisco",
        "Serce me zadrżało",
        "Shenandoah",
        "Siedzieliśmy jak w kinie",
        "Skrzydlate Ręce",
        "Someone like you",
        "Speak Softly, Love",
        "Śpiewać każdy może",
        "Spłynął mrok (Shadowland)",
        "Stary kowboj",
        "Stokrotka",
        "Strumień",
        "Świecie nasz",
        "Szary świat",
        "Szczęście",
        "Szyba",
        "Tak bardzo się starałem",
        "Tak bowiem Bóg",
        "Take me home, country roads",
        "Takie ładne oczy",
        "Takie tango",
        "Tango na głos, orkiestrę i jeszcze jeden głos",
        "Tango z garbem",
        "Tarnawatka",
        "Teksański",
        "Tell him",
        "Ten, który nie poznał",
        "Ten, który nie uwierzył",
        "Ten, który się zaparł",
        "Ten, który zdradził",
        "The sound of silence",
        "Timeraire",
        "To co spełni się",
        "Toss a Coin to Your Witcher",
        "Tu Es Petrus",
        "Ty przychodzisz jak noc majowa",
        "Tyle słońca w całym mieście",
        "Ucisz serce",
        "Victory",
        "W czasie deszczu dzieci się nudzą",
        "W górach",
        "W lesie listopadowym",
        "W moim ogródecku",
        "W naszym niebie",
        "Warneńczyk",
        "Warszawa",
        "Wciąż wierzę",
        "We śnie",
        "Wędrowiec",
        "Wehikuł czasu",
        "Wellerman",
        "Wesoły Roger",
        "What is a youth",
        "Whisky",
        "Wieczna noc (Endless Night)",
        "Wieczory",
        "Wielka woda",
        "Wiesna",
        "Wieża Babel",
        "Wilcza zamieć (Pieśń Priscilli)",
        "Wind of change",
        "Wish you were here",
        "Włosy",
        "Wodymidaj",
        "Wrecking Ball",
        "Wyspa",
        "Yesterday",
        "You raise me up",
        "Z nim będziesz szczęśliwsza",
        "Za siedmioma marzeniami",
        "Zabierzcie mi gitarę",
        "Zacznij od Bacha",
        "Zadumanie",
        "Zasmażka",
        "Zawsze tam, gdzie Ty",
        "Zdumienie",
        "Żeby móc (Prostota)",
        "Zegarmistrz światła",
        "Zemsta piratów",
        "Zielony mundur",
        "Znów wędrujemy",
        "Zombie",
        "Żono moja",
        "Zrobię mężczyzn z was",
        "Zwiewność",
    ],
    "patriotic": [
        "Bogurodzica",
        "Chłopcy silni jak stal",
        "Chorał",
        "Czerwone maki na Monte Cassino",
        "Deszcz, jesienny deszcz",
        "Dziś do Ciebie przyjść nie mogę",
        "Ej, dziewczyno, ej, niebogo",
        "Hej chłopcy, bagnet na broń",
        "Hymn Sybiraków",
        "Hymn szarych szeregów",
        "Idzie żołnierz borem lasem",
        "Jedzie na kasztance",
        "Jeszcze jeden mazur dzisiaj",
        "Marsz Mokotowa",
        "Marsz pierwszej brygady",
        "Marsz Polonii",
        "Marsz strzelców",
        "Mazurek 3 maja",
        "Modlitwa Armii Krajowej",
        "O mój rozmarynie",
        "Pałacyk Michla",
        "Pierwsza kadrowa",
        "Pieśń konfederatów barskich",
        "Przy sadzeniu róż",
        "Przybyli ułani",
        "Rota",
        "Rozkwitają pąki białych róż",
        "Rozszumiały się wierzby płaczące",
        "Serce w plecaku",
        "Święta miłości kochanej Ojczyzny",
        "Szara piechota",
        "Szary mundur",
        "Szturmówka",
        "Ułani, malowane dzieci",
        "Warczą karabiny",
        "Warszawianka",
        "Warszawo ma",
        "Warszawskie dzieci",
        "Wojenko, wojenko",
        "Żeby Polska była Polską",
    ],
    "religious": [
        "Będę śpiewał Tobie",
        "Bóg jest miłością",
        "Braciszkowie skrzydlaci",
        "Chlebie najcichszy",
        "Chrystus Pan karmi nas",
        "Chwalcie Pana narody",
        "Chwalę Ciebie Panie",
        "Cichy zapada zmrok",
        "Dym jałowca",
        "Gdyby wiara Twa",
        "Gloria",
        "Jeden jest tylko Pan",
        "Jedyny Pan",
        "Jezu, Tyś jest światłością mej duszy",
        "Jezus ratownik",
        "Jezus, najwyższe Imię",
        "Kiedy ranne wstają zorze",
        "Kiedy stanę przed Tobą",
        "Laudate Dominum",
        "Laudato sii",
        "Maryjo, maluczka Maryjo",
        "Memu Bogu, Królowi",
        "Miałem Pana zawsze przed oczami",
        "Mój Zbawiciel",
        "Nasze plany i nadzieje",
        "Nie bój się, nie lękaj się",
        "Nie ma takiego jak Jezus",
        "Nie ma większej miłości",
        "Niech zabrzmi Panu",
        "O mój najsłodszy Jezu",
        "Obudź się",
        "Oto jest dzień",
        "Oto stoję u drzwi",
        "Pan blisko jest",
        "Pan jest mocą swojego ludu",
        "Pan jest pasterzem moim",
        "Panie, Twój tron",
        "Panu naszemu pieśni grajcie",
        "Polorum Regina",
        "Przyobleczcie się w zbroję Bożą",
        "Raduje się dusza ma",
        "Schowaj mnie",
        "Święte Imię Jezus",
        "Tak mnie skrusz",
        "Tyś jak skała",
        "Ubi caritas",
        "Uwielbiajcie Pana",
        "Uwielbiam Imię Twoje Panie",
        "W drogę z nami",
        "W lekkim powiewie",
        "Wejdźmy do Jego bram",
        "Wielbić Pana chcę",
        "Wierzę w Ciebie Panie",
        "Wykrzykujcie na cześć Pana",
        "Wywyższony Bądź",
        "Zapada zmrok",
    ],
    "carols": [
        "Ach ubogi żłobie",
        "Adeste Fideles",
        "Anioł pasterzom mówił",
        "Bóg się rodzi",
        "Bracia, patrzcie jeno",
        "Cicha noc",
        "Do szopy, hej pasterze",
        "Dobryj weczir tobi",
        "Dzień jeden w roku",
        "Dzisiaj w Betlejem",
        "El burrito de Belén",
        "Gdy się Chrystus rodzi",
        "Gdy śliczna Panna",
        "Gore gwiazda Jezusowi",
        "Hej, w dzień narodzenia",
        "Jezus malusieńki",
        "Kolęda dla nieobecnych",
        "Kolęda dla Piotra Skrzyneckiego",
        "Kolęda Maryi",
        "Los Peces en el Río",
        "Lulajże Jezuniu",
        "Mędrcy świata",
        "Mizerna Cicha",
        "Nie było miejsca dla Ciebie",
        "O gwiazdo Betlejemska",
        "Oj, maluśki, maluśki",
        "Pójdźmy wszyscy do stajenki",
        "Północ już była",
        "Pomaluśku Józefie",
        "Przybieżeli do Betlejem",
        "Świeć gwiazdeczko",
        "Święta noc",
        "To już pora na Wigilię",
        "Tryumfy Króla Niebieskiego",
        "Uciekali",
        "W żłobie leży",
        "Wesołą nowinę",
        "Wśród nocnej ciszy",
        "Z narodzenia Pana",
        "Zaśnij Dziecino",
        "Złota Jerozolima i biedne Betlejem",
    ]
}
